/**
 * POST /api/supplements/unified
 * Phase 2: Single guided flow combining OCR, analyze, supplement with carrier intel
 *
 * Body:
 *   - estimateId?: string (from xactimate_estimates - use existing analysis)
 *   - adjusterEstimate?: string (raw text)
 *   - carrier?: string (carrier slug for win pack / rationale)
 *   - state: string
 *   - damageType: string
 *   - roofType?: string
 *
 * Returns: ranked line items, evidence checklist, carrier rationale, structured export, disclaimer
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { resolveWriteTeamIdForUser } from "@/lib/server/tenant";
import { checkFeatureAccess } from "@/lib/subscriptions";
import { recordAIUsage } from "@/lib/ai-usage/record";
import { emitWebhook } from "@/lib/webhooks/emit";
import OpenAI from "openai";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const SUPPLEMENT_DISCLAIMER = `---
This supplement analysis was generated by StormClose AI as a companion tool to Xactimate and your estimating workflow. 
It is not licensed estimating software. Verify all line items, codes, and values before submission to carriers.
---`;

export async function POST(request: NextRequest) {
	try {
		const supabase = await createClient();
		const { data: { user } } = await supabase.auth.getUser();

		if (!user) {
			return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
		}

		const access = await checkFeatureAccess(user.id, "supplement_generator");
		if (!access.allowed) {
			return NextResponse.json(
				{ error: access.reason, tier: access.tier },
				{ status: 403 }
			);
		}

		const body = await request.json().catch(() => ({}));
		const {
			estimateId,
			adjusterEstimate,
			carrier = "unknown",
			state,
			damageType,
			roofType,
			propertyAge,
		} = body;

		let estimateText = adjusterEstimate;

		if (estimateId) {
			const { data: est, error } = await (supabase as any)
				.from("xactimate_estimates")
				.select("*")
				.eq("id", estimateId)
				.eq("user_id", user.id)
				.single();

			if (error || !est) {
				return NextResponse.json({ error: "Estimate not found" }, { status: 404 });
			}

			estimateText =
				est.raw_data
					? JSON.stringify(est.raw_data)
					: [
							`Carrier: ${est.insurance_carrier}`,
							`RCV: $${est.original_rcv}`,
							`ACV: $${est.original_acv}`,
							`Depreciation: $${est.depreciation}`,
							est.ai_analysis ? `Analysis: ${JSON.stringify(est.ai_analysis)}` : "",
						]
							.filter(Boolean)
							.join("\n");
		}

		if (!estimateText) {
			return NextResponse.json({ error: "Provide estimateId or adjusterEstimate" }, { status: 400 });
		}

		if (!state || !damageType) {
			return NextResponse.json({ error: "state and damageType required" }, { status: 400 });
		}

		// Fetch carrier win pack if available (user's own, team's, or global)
		let winPack: { usuallyPasses: unknown[]; usuallyFights: unknown[] } = { usuallyPasses: [], usuallyFights: [] };
		const carrierSlug = String(carrier).toLowerCase().replace(/\s+/g, "-");
		try {
			const { data: userPack } = await (supabase as any)
				.from("carrier_win_packs")
				.select("usually_passes, usually_fights")
				.eq("carrier_slug", carrierSlug)
				.eq("user_id", user.id)
				.is("effective_to", null)
				.order("version", { ascending: false })
				.limit(1)
				.maybeSingle();

			const pack = userPack;
			if (pack) {
				winPack = {
					usuallyPasses: pack.usually_passes ?? [],
					usuallyFights: pack.usually_fights ?? [],
				};
			}
		} catch {
			// Table may not exist yet or RLS blocks; proceed without win pack
		}

		const completion = await openai.chat.completions.create({
			model: "gpt-4o-mini",
			messages: [
				{
					role: "system",
					content: `You are an expert roofing insurance supplement specialist. Analyze estimates and return a structured JSON response.
Format: { "rankedLineItems": [...], "evidenceChecklist": [...], "carrierRationale": "...", "supplementText": "..." }
- rankedLineItems: [{ lineItem, xactCode, estimatedValue, confidence, justification }] - sorted by confidence desc
- evidenceChecklist: [ strings of what to document ]
- carrierRationale: 2-3 sentences specific to this carrier
- supplementText: professional supplement request (sections, bullets)`,
				},
				{
					role: "user",
					content: `Analyze this estimate for supplements.

State: ${state}
Damage: ${damageType}
${roofType ? `Roof: ${roofType}` : ""}
${propertyAge ? `Property age: ${propertyAge} yrs` : ""}
Carrier context: ${carrierSlug}
${winPack.usuallyPasses.length ? `Often passes: ${JSON.stringify(winPack.usuallyPasses)}` : ""}
${winPack.usuallyFights.length ? `Often fights: ${JSON.stringify(winPack.usuallyFights)}` : ""}

Estimate:
${estimateText.slice(0, 12000)}

Return valid JSON only.`,
				},
			],
			temperature: 0.5,
			max_tokens: 2500,
		});

		const raw = completion.choices[0]?.message?.content?.trim() ?? "{}";
		let parsed: {
			rankedLineItems?: Array<{ lineItem: string; xactCode: string; estimatedValue: number; confidence: number; justification: string }>;
			evidenceChecklist?: string[];
			carrierRationale?: string;
			supplementText?: string;
		} = {};
		try {
			const match = raw.match(/\{[\s\S]*\}/);
			parsed = JSON.parse(match ? match[0] : "{}");
		} catch {
			parsed = { supplementText: raw };
		}

		const rankedLineItems = parsed.rankedLineItems ?? [];
		const evidenceChecklist = parsed.evidenceChecklist ?? [];
		const carrierRationale = parsed.carrierRationale ?? "";
		const supplementText = (parsed.supplementText ?? "").trim();

		const structuredExport = formatStructuredExport({
			rankedLineItems,
			evidenceChecklist,
			carrierRationale,
			supplementText,
			disclaimer: SUPPLEMENT_DISCLAIMER,
		});

		const teamId = await resolveWriteTeamIdForUser(supabase, user.id, null).catch(() => null);
		await recordAIUsage({ userId: user.id, teamId, feature: "supplement_unified" });
		if (teamId) {
			emitWebhook(teamId, "supplement_ready", {
				carrier: carrierSlug,
				state,
				rankedCount: rankedLineItems.length,
			}).catch(() => {});
		}

		return NextResponse.json({
			success: true,
			rankedLineItems,
			evidenceChecklist,
			carrierRationale,
			supplementText,
			structuredExport,
			disclaimer: SUPPLEMENT_DISCLAIMER,
			metadata: {
				carrier: carrierSlug,
				state,
				damageType,
				generatedAt: new Date().toISOString(),
			},
		});
	} catch (error) {
		console.error("Unified supplement error:", error);
		return NextResponse.json(
			{ error: "Supplement generation failed", details: String(error) },
			{ status: 500 }
		);
	}
}

function formatStructuredExport(ctx: {
	rankedLineItems: Array<{ lineItem: string; xactCode: string; estimatedValue: number; justification: string }>;
	evidenceChecklist: string[];
	carrierRationale: string;
	supplementText: string;
	disclaimer: string;
}): string {
	const sections: string[] = [];

	sections.push("# SUPPLEMENT REQUEST\n");
	sections.push("## Missing / Underpaid Line Items\n");
	ctx.rankedLineItems.forEach((item, i) => {
		sections.push(`### ${i + 1}. ${item.lineItem}`);
		sections.push(`- **Code:** ${item.xactCode || "TBD"}`);
		if (item.estimatedValue) sections.push(`- **Est. Value:** $${item.estimatedValue.toLocaleString()}`);
		sections.push(`- **Justification:** ${item.justification}\n`);
	});

	sections.push("## Evidence Checklist\n");
	ctx.evidenceChecklist.forEach((item) => sections.push(`- [ ] ${item}`));

	if (ctx.carrierRationale) {
		sections.push("\n## Carrier-Specific Notes\n");
		sections.push(ctx.carrierRationale);
	}

	sections.push("\n---\n## Full Supplement Text\n\n");
	sections.push(ctx.supplementText);
	sections.push("\n\n");
	sections.push(ctx.disclaimer);

	return sections.join("\n");
}
